version: '3.8'

services:
  db:
    image: postgres:17
    container_name: management_system_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: management_system
    ports:
      - "5432:5432"